#4 | Added countLogger
getthere-dataunit/spark-utils pull request #9
Opened 2020-08-18 21:08 UTC by ferdyh

2020-08-18 21:18 UTC, frankivo requested changes

2020-08-18 21:18 UTC, frankivo commented on src/main/scala/nl/getthere/dataunit/spark/utils/run/CountLogger.scala
> +      .mode(SaveMode.Append)
prefer "append" to save the import

2020-08-18 21:18 UTC, frankivo commented on src/test/scala/nl/getthere/dataunit/spark/utils/run/CountLoggerTest.scala
> +  Directory(new java.io.File("./spark-warehouse")).deleteRecursively()
should we do this at the end of the tests too?

2020-08-18 21:23 UTC, ferdyh commented on src/main/scala/nl/getthere/dataunit/spark/utils/run/CountLogger.scala
> +      .mode(SaveMode.Append)
Wrote it wrong few times... This atleast gets picked up by the compiler; Prefer it in notebooks aswell, but maybe in library this is better..? IDE helps you anyways.

2020-08-18 21:25 UTC, ferdyh commented on src/test/scala/nl/getthere/dataunit/spark/utils/run/CountLoggerTest.scala
> +  Directory(new java.io.File("./spark-warehouse")).deleteRecursively()
I'm not really sure; Before you're atleast certain its all right for these tests. Ofcourse cleaning up afterwards is neat. Probably need create an issue to fix pre and post test stuff, and maybe a test data model?

2020-08-19 06:54 UTC, frankivo commented on src/main/scala/nl/getthere/dataunit/spark/utils/run/CountLogger.scala
> +      .mode(SaveMode.Append)
ok :)

2020-08-19 06:55 UTC, frankivo commented on src/test/scala/nl/getthere/dataunit/spark/utils/run/CountLoggerTest.scala
> +  Directory(new java.io.File("./spark-warehouse")).deleteRecursively()
Yep, let's do that later

2020-08-19 06:56 UTC, frankivo approved these changes

2020-08-19 06:56 UTC, merged